redis:
  image: redis:alpine
  command: redis-server --requirepass password
  container_name: redis
  ports:
    - "6379:6379"
mongo:
  image: mvertes/alpine-mongo
  container_name: mongo
  ports:
    - "27017:27017"
